### ISSUE TITLE
how to run the application in local machine with offline

### ISSUE THREAD

**Issue by SrinivasanMuthukannu** [IndomaximTechID/storaji-ui#3]
how to run the application in local machine with offline.

**Comment by eriestrisnadi** [comment]
First of all, thanks for taking an interest on storaji. But, unfornately the app that already built on the release page needs an internet to connect to the server. For now, storaji can't do such an offline mode to works. I was thinking about offline works for the official release of v1.0.0.

But, if you cant wait for it. You can build it from the source, first you need to clone the backend located at https://github.com/IndomaximTechID/storaji and the frontend located at https://github.com/IndomaximTechID/storaji-ui

I will create steps how to build from source on the wiki page when I got a free time, please be patient. Thank you.

**Comment by eriestrisnadi** [comment]
I have updated `README.md`, You can check [Development Section](https://github.com/IndomaximTechID/storaji-ui/blob/master/readme.md#development) to setup your app hosted on your local machine. Thanks!
