### ISSUE TITLE
Cant open frontend Page

### ISSUE THREAD

**Issue by fahreza007** [IndomaximTechID/storaji-ui#6]
![image](https://user-images.githubusercontent.com/11717937/43555715-1d404430-9626-11e8-8560-f6a32bd757b3.png)

![43555715-1d404430-9626-11e8-8560-f6a32bd757b3](https://user-images.githubusercontent.com/11717937/43555729-3806549e-9626-11e8-9b84-e577d4d45db5.png)

Excuse me sir, I'm from indonesia
i try to install your project but i have problem on frontend page (storaji-ui) after npm install so i do next step npm run ng:serve & on my web browse i visit https://localhost:4200 but i cannot open my frontend.

What wrong? Thank you

**Comment by eriestrisnadi** [comment]
I think it's not https protocol, since if you have not set up self signed certificate. Try it on http instead, remember without "s".

**Comment by fahreza007** [comment]
Yes sir thank you. But now i have new problem. Why i cant sign in to
localhost:4200
Name : admin@demo.com
Pass : secret

Cant login.

**Comment by eriestrisnadi** [comment]
Have you setup the backend and your db connection in ```.env``` file already? If yes, let me know, also if you provide me some screenshot it will be great.

**Comment by ramjisubedi** [comment]
sir when the code is built into the .exe file then how to manage the database because the user can't install any server.
how to create an offline server. like working in this storaji app

**Comment by eriestrisnadi** [comment]
You need to install the backend server, of course you need a Webserver like an Apache/nginx, PHP 7 and one of Database (MySQL, Sqlite, etc) on your local machine in order to run the backend.

When you have install all, see the backend installation on the readme file.

*If you use the windows, just install wamp or xampp because all of the requires have been included.

**Comment by fahreza007** [comment]
ok thankyou.

**Comment by ramjisubedi** [comment]
thank you @lowsprofile ok its works when I install xamp server. after build to .exe file is there compulsory to install xamp or wamp for the run this app. because of the users cannot install any server.

**Comment by eriestrisnadi** [comment]
@fahreza007 no problem dude.

@ramjisubedi you can't run it without a webserver. Other choice is to connect it to our server, but the user must have only an internet.
